// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoptionMAUI.Api.Data;

#nullable disable

namespace PetAdoptionMAUI.Api.Data.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20250525182825_SeedMoreNewData")]
    partial class SeedMoreNewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdpotionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdpotionStatus = 1,
                            Breed = "Golden Retriever",
                            Category = 0,
                            DateOfBirth = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Дружелюбна и енергична, Бела обича да играе и да прави дълги разходки. Тя се разбира чудесно с деца и други домашни любимци.",
                            Gender = 1,
                            Image = "bella.jpg",
                            IsActive = true,
                            Name = "Бела",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            AdpotionStatus = 1,
                            Breed = "Bulldog",
                            Category = 0,
                            DateOfBirth = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Дейзи е игрив и дружелюбен лабрадор. Обича водата и обича да плува в езерото.",
                            Gender = 1,
                            Image = "dog3.jpg",
                            IsActive = true,
                            Name = "Дейзи",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdpotionStatus = 1,
                            Breed = "Bulldog",
                            Category = 0,
                            DateOfBirth = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Макс е спокоен и любящ булдог. Обича да се излежава наоколо и е много лоялен към семейството си.",
                            Gender = 0,
                            Image = "dog1.jpg",
                            IsActive = true,
                            Name = "Макс",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            AdpotionStatus = 1,
                            Breed = "Beagle",
                            Category = 0,
                            DateOfBirth = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Чарли е любопитен и игрив бигъл. Обича да изследва и е много приятелски настроен към всеки, когото срещне.",
                            Gender = 0,
                            Image = "dog2.jpg",
                            IsActive = true,
                            Name = "Чарли",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            AdpotionStatus = 1,
                            Breed = "Siamese Cat",
                            Category = 1,
                            DateOfBirth = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Люси е красива сиамска котка с поразително сини очи. Тя е независима, но обича да се гушка, когато е в настроение.",
                            Gender = 1,
                            Image = "cat1.jpg",
                            IsActive = true,
                            Name = "Люси",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            AdpotionStatus = 1,
                            Breed = "Persian Cat",
                            Category = 1,
                            DateOfBirth = new DateTime(2024, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Майло е пухкава котка, която обича да се излежава на слънчеви места. Той е кротък и обича да бъде глезен.",
                            Gender = 1,
                            Image = "cat2.jpg",
                            IsActive = true,
                            Name = "Майло",
                            Price = 180.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            AdpotionStatus = 1,
                            Breed = "German Shepherd",
                            Category = 0,
                            DateOfBirth = new DateTime(2025, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Роки е силна и интелигентна немска овчарка. Той защитава семейството си и обича да играе.",
                            Gender = 0,
                            Image = "germanShepard.jpg",
                            IsActive = true,
                            Name = "Роки",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            AdpotionStatus = 1,
                            Breed = "Senegal parrot",
                            Category = 2,
                            DateOfBirth = new DateTime(2024, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Луна е жив и разговорлив сенегалски папагал. Тя обича да имитира звуци и обича да общува с хора.",
                            Gender = 1,
                            Image = "senegalParrot.jpg",
                            IsActive = true,
                            Name = "Луна",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 9,
                            AdpotionStatus = 1,
                            Breed = "Cockatiel",
                            Category = 2,
                            DateOfBirth = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Coco е сладък и дружелюбен коктейл. Обича да пее и да танцува, когато чуе музика.",
                            Gender = 0,
                            Image = "bird1.jpg",
                            IsActive = true,
                            Name = "Coco",
                            Price = 180.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 10,
                            AdpotionStatus = 1,
                            Breed = "Lark",
                            Category = 2,
                            DateOfBirth = new DateTime(2024, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Бъни е сладък и пухкав. Обича да играе с играчките си. Идеален домашен любимец за деца.",
                            Gender = 0,
                            Image = "bird2.jpg",
                            IsActive = true,
                            Name = "Бъни",
                            Price = 50.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 11,
                            AdpotionStatus = 1,
                            Breed = "Sparrow",
                            Category = 2,
                            DateOfBirth = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Снежи е енергична и игрива. Обича да подскача и да играе с деца.",
                            Gender = 1,
                            Image = "bird3.jpg",
                            IsActive = true,
                            Name = "Снежи",
                            Price = 400.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 12,
                            AdpotionStatus = 1,
                            Breed = "Българска котка",
                            Category = 1,
                            DateOfBirth = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Блу е мила и игрива българска котка. Тя обича да се гушка и да играе с топки.",
                            Gender = 1,
                            Image = "cat3.jpg",
                            IsActive = true,
                            Name = "Блу",
                            Price = 120.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 13,
                            AdpotionStatus = 1,
                            Breed = "Българска котка",
                            Category = 1,
                            DateOfBirth = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Том е дружелюбен и игрив български котарак. Той обича да се разхожда наоколо и да изследва.",
                            Gender = 0,
                            Image = "cat4.jpg",
                            IsActive = true,
                            Name = "Том",
                            Price = 130.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 14,
                            AdpotionStatus = 1,
                            Breed = "Българска котка",
                            Category = 1,
                            DateOfBirth = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Фреди е пухкав и игрив български котарак. Той обича да се гушка и да играе с деца.",
                            Gender = 0,
                            Image = "cat5.jpg",
                            IsActive = true,
                            Name = "Фреди",
                            Price = 140.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 15,
                            AdpotionStatus = 1,
                            Breed = "Българска котка",
                            Category = 1,
                            DateOfBirth = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Зара е мила и игрива българска котка. Тя обича да се гушка и да играе с топки.",
                            Gender = 1,
                            Image = "cat6.jpg",
                            IsActive = true,
                            Name = "Зара",
                            Price = 110.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 16,
                            AdpotionStatus = 1,
                            Breed = "Българска котка",
                            Category = 1,
                            DateOfBirth = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Бобо е дружелюбен и игрив български котарак. Той обича да се разхожда наоколо и да изследва.",
                            Gender = 0,
                            Image = "cat7.jpg",
                            IsActive = true,
                            Name = "Бобо",
                            Price = 115.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 17,
                            AdpotionStatus = 1,
                            Breed = "Пухкава Снежинка",
                            Category = 0,
                            DateOfBirth = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Снежинка е пухкава и игрива българско куче. Обича да се гушка и да играе с деца.",
                            Gender = 1,
                            Image = "dog4.jpg",
                            IsActive = true,
                            Name = "Снежинка",
                            Price = 125.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 18,
                            AdpotionStatus = 1,
                            Breed = "Океанска Риба",
                            Category = 3,
                            DateOfBirth = new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Бобо е красива океанска риба с ярки цветове. Той е спокоен и обича да плува в аквариума.",
                            Gender = 0,
                            Image = "fish1.jpg",
                            IsActive = true,
                            Name = "Бобо",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 19,
                            AdpotionStatus = 1,
                            Breed = "Златна Рибка",
                            Category = 3,
                            DateOfBirth = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Златко е класическа златна рибка с блестящи люспи. Тя е спокойна и обича да плува в аквариума.",
                            Gender = 0,
                            Image = "fish2.jpg",
                            IsActive = true,
                            Name = "Златко",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 20,
                            AdpotionStatus = 1,
                            Breed = "Тропическа Риба",
                            Category = 3,
                            DateOfBirth = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Поко е ярка и цветна тропическа риба. Тя обича да плува в аквариума и да се наслаждава на топлата вода.",
                            Gender = 0,
                            Image = "fish3.jpg",
                            IsActive = true,
                            Name = "Поко",
                            Price = 200.0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoptions");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserFavorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserAdoption", b =>
                {
                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserFavorites", b =>
                {
                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
