// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetAdoptionMAUI.Api.Data;

#nullable disable

namespace PetAdoptionMAUI.Api.Data.Migrations
{
    [DbContext(typeof(PetContext))]
    [Migration("20250524163412_SeedNewData")]
    partial class SeedNewData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdpotionStatus")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Views")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Pets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdpotionStatus = 1,
                            Breed = "Golden Retriever",
                            Category = 0,
                            DateOfBirth = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Friendly and energetic, Bella loves to play fetch and go for long walks. She's great with kids and other pets.",
                            Gender = 1,
                            Image = "bella.jpg",
                            IsActive = true,
                            Name = "Bella",
                            Price = 300.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 2,
                            AdpotionStatus = 1,
                            Breed = "Bulldog",
                            Category = 0,
                            DateOfBirth = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Max is a calm and affectionate bulldog. He enjoys lounging around and is very loyal to his family.",
                            Gender = 0,
                            Image = "dog1.jpg",
                            IsActive = true,
                            Name = "Max",
                            Price = 250.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 3,
                            AdpotionStatus = 1,
                            Breed = "Beagle",
                            Category = 0,
                            DateOfBirth = new DateTime(2021, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Charlie is a curious and playful beagle. He loves to explore and is very friendly with everyone he meets.",
                            Gender = 0,
                            Image = "dog2.jpg",
                            IsActive = true,
                            Name = "Charlie",
                            Price = 200.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 4,
                            AdpotionStatus = 1,
                            Breed = "Siamese Cat",
                            Category = 1,
                            DateOfBirth = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lucy is a beautiful Siamese cat with striking blue eyes. She's independent but loves to cuddle when she's in the mood.",
                            Gender = 1,
                            Image = "cat1.jpg",
                            IsActive = true,
                            Name = "Lucy",
                            Price = 150.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 5,
                            AdpotionStatus = 1,
                            Breed = "Persian Cat",
                            Category = 1,
                            DateOfBirth = new DateTime(2021, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Milo is a fluffy Persian cat who enjoys lounging in sunny spots. He's gentle and loves being pampered.",
                            Gender = 1,
                            Image = "cat2.jpg",
                            IsActive = true,
                            Name = "Milo",
                            Price = 180.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 6,
                            AdpotionStatus = 1,
                            Breed = "Labrador Retriever",
                            Category = 0,
                            DateOfBirth = new DateTime(2020, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Daisy is a playful and friendly Labrador. She loves water and enjoys swimming in the lake.",
                            Gender = 1,
                            Image = "dog3.jpg",
                            IsActive = true,
                            Name = "Daisy",
                            Price = 320.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 7,
                            AdpotionStatus = 1,
                            Breed = "German Shepherd",
                            Category = 0,
                            DateOfBirth = new DateTime(2021, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Rocky is a strong and intelligent German Shepherd. He's protective of his family and loves to play fetch.",
                            Gender = 0,
                            Image = "germanShepard.jpg",
                            IsActive = true,
                            Name = "Rocky",
                            Price = 350.0,
                            Views = 0
                        },
                        new
                        {
                            Id = 8,
                            AdpotionStatus = 1,
                            Breed = "Senegal parrot",
                            Category = 2,
                            DateOfBirth = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Luna is a vibrant and talkative Senegal parrot. She loves to mimic sounds and enjoys interacting with people.",
                            Gender = 1,
                            Image = "senegalParrot.jpg",
                            IsActive = true,
                            Name = "Luna",
                            Price = 400.0,
                            Views = 0
                        });
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserAdoption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AdoptionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAdoptions");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserFavorites", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PetId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("UserFavorites");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserAdoption", b =>
                {
                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PetAdoptionMAUI.Api.Data.Entities.UserFavorites", b =>
                {
                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetAdoptionMAUI.Api.Data.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
